[phases.setup]
nixPkgs = ["...", "php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.json", "php82Extensions.zip", "php82Extensions.gd", "php82Extensions.intl"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "php -S 0.0.0.0:$PORT index.php"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/"
NIXPACKS_PHP_FALLBACK_PATH = "/index.php"
